version: '3.9'

services:
  mysql_main_db:
    image: mysql
    container_name: ${MYSQL_MAIN_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_MAIN_DB_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - 6602:${MYSQL_MAIN_DB_PORT}
    volumes:
      - ./db_data/mysql_main_db:/var/libs/mysql
    networks:
      - backend

  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 6603:${DB_PORT}
    volumes:
      - ./db_data:/var/libs/mysql
    networks:
      - backend


  mongo_main_db:
    image: mongo
    container_name: ${MONGO_DB_CONTAINER_HOST}
    restart: always
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    volumes:
      - ./db_data/mongo_main_db:/var/libs/mongodb
    networks:
      - backend


  support_cache_redis:
    image: redis:7.0-alpine
    container_name: ${REDIS_HOST}
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./db_data/redis_support_cache:/data
    networks:
      - backend


  server:
    container_name: main_server
    working_dir: /app
    depends_on:
      - mysql_main_db
      - mariadb
      - mongo_main_db
      - support_cache_redis
    build:
      context: .
      dockerfile: Dockerfile.yarn
    ports:
      - ${MAIN_SERVER_PORT}:${MAIN_SERVER_PORT}
    volumes:
      - ./:/app
    networks:
      - backend


volumes:
  mysql_main_db:
    driver: local
  mariadb:
    driver: local
  mongo_main_db:
    driver: local
  redis_support_cache:
    driver: local


networks:
  backend:
    driver: bridge
